services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    # environment:
    #   - POSTGRES_DB : "OnlineStoreDb"
    #   - POSTGRES_USER : "postgres"
    #   - POSTGRES_PASSWORD : "Sugar"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork 
    restart: always 

# Надо подключить еще бд
  backend:
    container_name: OnlineStore
    build:
      context: ./backend/OnlineStore
      dockerfile: Dockerfile
    ports:
      - "5200:5200"
    env_file: #Jwt__SecretKey ConnectionString
      - .env 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - api_data:/app/data
    networks:
      - mynetwork
    depends_on:
      - postgres
    restart: always 

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   networks:
  #     - mynetwork
  #   depends_on:
  #     - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - mynetwork
    depends_on:
      # - frontend
      - backend
    restart: always 

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data:
  api_data:
